_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.5
            "6": 4.48.2
            "8":
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
batch_size:
    value: 32
class_weights:
    value:
        identity_hate: 5.45
        insult: 0.91
        obscene: 1
        severe_toxic: 5.88
        threat: 33.33
        toxic: 0.54
device:
    value: cpu
epochs:
    value: 5
grad_accum_steps:
    value: 2
languages:
    value:
        - en
        - ru
        - fr
        - it
        - es
        - pt
        - tr
lr:
    value: 2e-05
max_length:
    value: 128
model_name:
    value: xlm-roberta-large
num_gpus:
    value: 0
